### PR TITLE
Unicode characters support

### PR DESCRIPTION
**Pull request by i7an**
According to [Wiki](http://en.wikipedia.org/wiki/Email_address#Valid_email_addresses) you can use unicode symbols.

### CODE REVIEW

**Comment by ascrazy** [comment]
+1

**Comment by vitalyperminov** [comment]
+1

**Comment by Galathius** [comment]
:100: :100: :100:

**Comment by vladimir-tikhonov** [comment]
+3

**Comment by mhuggins** [comment]
+4

**Comment by balexand** [comment]
Thanks, and sorry for the delay.

**Pull request merged**
